### ISSUE TITLE
L1 - FERRITE BEAD 220 OHM is no longer manufactured

### ISSUE THREAD

**Issue by Muhammad-Salmun** [LinnesLab/KickStat-Paper-Firmware#3]
30Ohm Inductor - L1 - FERRITE BEAD 220 OHM 0603 - [CIS10P221NC](https://www.digikey.in/en/products/detail/samsung-electro-mechanics/CIS10P221NC/3973857)
is no longer manufactured, will [BLM18SG221TN1D](https://in.element14.com/murata/blm18eg221sn1d/ferrite-bead-0-05ohm-2a-0603/dp/1515716?CMP=KNC-GIN-GEN-DSA-PDP-PAGE-RESTOFIND_CITY_TEST-Split-S30&mckv=s_dc|pcrid|576092813678|pkw||pmt||slid||product||pgrid|100159060006|ptaid|aud-136190172280:dsa-906758374001|&gclid=CjwKCAjwivemBhBhEiwAJxNWN6n5whyE7YobiIj8ah1zVJR9dS0ZgKKcwzxiaflFuM4sDNXUuXd6ahoCr80QAvD_BwE) be sufficient?
Else, what will be a better replacement?

**Comment by hoilett** [comment]
Hi,

Yes, the one you selected should be fine.

----
Orlando S. Hoilett, Ph.D.
***@***.***
